# Generated by Django 4.2.14 on 2024-08-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='email'),
        ),
    ]
