# Generated by Django 4.2.15 on 2024-08-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_friendship_delete_testu_remove_message_receiver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='User1',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='User2',
            new_name='user2',
        ),
    ]
