# Generated by Django 5.1 on 2024-08-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_user1_friendship_user1_and_more'),
        ('users', '0003_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.AlterField(
            model_name='message',
            name='friendshipid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='users.friendship'),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='FriendShip',
        ),
    ]
