# Generated by Django 5.1 on 2024-09-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=150)),
                ('player2', models.CharField(max_length=150)),
                ('final_winner', models.CharField(blank=True, max_length=200, null=True)),
                ('score_x', models.IntegerField(default=0, verbose_name='Score X')),
                ('score_o', models.IntegerField(default=0, verbose_name='Score O')),
                ('game_start', models.DateField(auto_now_add=True, verbose_name='Game Start')),
                ('game_end', models.DateField(auto_now=True, verbose_name='Game End')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
