# Generated by Django 5.1 on 2024-09-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameonline',
            options={'ordering': ['startTime']},
        ),
    ]
