# Generated by Django 5.1 on 2024-09-04 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_alter_gameonline_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameonline',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameonline',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_home', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameonline',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_away', to=settings.AUTH_USER_MODEL),
        ),
    ]
