# Generated by Django 5.1 on 2024-09-04 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0003_gameonline_is_start_alter_gameonline_player1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameonline',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home', to=settings.AUTH_USER_MODEL),
        ),
    ]
