# Generated by Django 5.1 on 2024-09-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0005_alter_gameonline_player1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoffline',
            name='player1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gameoffline',
            name='player2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
