# Generated by Django 5.1 on 2024-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0006_alter_gameoffline_player1_alter_gameoffline_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoffline',
            name='winner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
