# Generated by Django 5.1 on 2024-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_alter_gameonline_options'),
        ('tournament', '0005_alter_tournament_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(blank=True, to='pingpong.gameonline'),
        ),
    ]
