# Generated by Django 5.1 on 2024-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournament_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='knockout',
            field=models.IntegerField(default=4),
        ),
    ]
