# Generated by Django 5.1 on 2024-09-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_invitetournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
