# Generated by Django 5.1 on 2024-09-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournamentlocal_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='PlayerLocal',
        ),
    ]
