# Generated by Django 5.1 on 2024-08-28 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 14, 17, 24, 169006, tzinfo=datetime.timezone.utc)),
        ),
    ]
