# Generated by Django 5.1 on 2024-08-28 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
