# Generated by Django 5.1 on 2024-09-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_last_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
